---
RecipeFormatVersion: "2020-01-25"
ComponentName: "COMPONENT_NAME"
ComponentVersion: "COMPONENT_VERSION"
ComponentDescription: "This is simple Hello World component written in Native Java."
ComponentPublisher: "COMPONENT_AUTHOR"
ComponentConfiguration:
  DefaultConfiguration:
    Message: "World"
Manifests:
  - Platform:
      os: linux
      arch: aarch64
    Artifacts:
      - URI: "s3://BUCKET_NAME/COMPONENT_NAME/COMPONENT_VERSION/COMPONENT_NAME.zip"
        Unarchive: "ZIP"
    Lifecycle:
      Install: "chmod +x {artifacts:decompressedPath}/COMPONENT_NAME/application"
      Run: "{artifacts:decompressedPath}/COMPONENT_NAME/application {configuration:/Message}"